-- NYPD Complaint Data Historic Table
CREATE TABLE nypd_complaints (
    CMPLNT_NUM INT PRIMARY KEY,
	ADDR_PCT_CD DOUBLE PRECISION,
	BORO_NM VARCHAR(255),
    CMPLNT_FR_DT DATE,
    CMPLNT_FR_TM TIME,
    CMPLNT_TO_DT DATE,
    CMPLNT_TO_TM TIME,
	CRM_ATPT_CPTD_CD VARCHAR(255),
	HADEVELOPT VARCHAR(255),
	HOUSING_PSA INT,
	JURISDICTION_CODE INT,
	JURIS_DESC VARCHAR(255),
	KY_CD INT,
	LAW_CAT_CD VARCHAR(255),
	LOC_OF_OCCUR_DESC VARCHAR(255),
	OFNS_DESC VARCHAR(255),
	PARKS_NM VARCHAR(255),
	PATROL_BORO VARCHAR(255),
	PD_CD INT,
	PD_DESC VARCHAR(255),
	PREM_TYP_DESC VARCHAR(255),
    RPT_DT DATE,
    STATION_NAME VARCHAR(255),
    SUSP_AGE_GROUP VARCHAR(255),
    SUSP_RACE VARCHAR(255),
    SUSP_SEX VARCHAR(255),
    TRANSIT_DISTRICT INT,
    VIC_AGE_GROUP VARCHAR(255),
    VIC_RACE VARCHAR(255),
    VIC_SEX VARCHAR(255),
    X_COORD_CD INT,
    Y_COORD_CD INT,
    Latitude DOUBLE PRECISION,
    Longitude DOUBLE PRECISION,
    Lat_Lon VARCHAR(255),
	"New Georeferenced Column" VARCHAR(255),
	Year INT
);

-- NY Holiday List Table
CREATE TABLE ny_holidays (
    Date DATE PRIMARY KEY,
    Holiday VARCHAR(255),
    Weekday VARCHAR(255),
    Month VARCHAR(255),
    Day INT,
    Year INT
);

-- NYC Daily Temperature Table
CREATE TABLE nyc_temperature (
    "MM/DD/YYYY" DATE PRIMARY KEY,
    YEAR INT,
    MONTH INT,
    DAY INT,
    TMAX INT,
    TMIN INT
);

-- Copy data from CSV files (replace file paths accordingly)
COPY nypd_complaints FROM 'C:\Program Files\PostgreSQL\NYPD_Data_2003_sql.csv' DELIMITER ',' CSV HEADER;
COPY ny_holidays FROM 'C:\Program Files\PostgreSQL\holidays_list_sql.csv' DELIMITER ',' CSV HEADER;
COPY nyc_temperature FROM 'C:\Program Files\PostgreSQL\temp_nyc_sql.csv' DELIMITER ',' CSV HEADER;

SELECT * FROM nypd_complaints;

-- Drop Unwanted Columns
ALTER TABLE nypd_complaints
DROP COLUMN IF EXISTS CMPLNT_TO_DT,
DROP COLUMN IF EXISTS CMPLNT_TO_TM,
DROP COLUMN IF EXISTS HADEVELOPT,
DROP COLUMN IF EXISTS HOUSING_PSA,
DROP COLUMN IF EXISTS JURISDICTION_CODE,
DROP COLUMN IF EXISTS JURIS_DESC,
DROP COLUMN IF EXISTS PARKS_NM,
DROP COLUMN IF EXISTS PATROL_BORO,
DROP COLUMN IF EXISTS PD_CD,
DROP COLUMN IF EXISTS PD_DESC,
DROP COLUMN IF EXISTS STATION_NAME,
DROP COLUMN IF EXISTS TRANSIT_DISTRICT,
DROP COLUMN IF EXISTS X_COORD_CD,
DROP COLUMN IF EXISTS Y_COORD_CD,
DROP COLUMN IF EXISTS Latitude,
DROP COLUMN IF EXISTS Longitude,
DROP COLUMN IF EXISTS Lat_Lon,
DROP COLUMN IF EXISTS "New Georeferenced Column";

-- View nypd_complaints headings
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'nypd_complaints';

-- Handle Missing Data
UPDATE nypd_complaints
SET
  OFNS_DESC = CASE WHEN OFNS_DESC = '(null)' THEN NULL ELSE OFNS_DESC END,
  CRM_ATPT_CPTD_CD = CASE WHEN CRM_ATPT_CPTD_CD = '(null)' THEN NULL ELSE CRM_ATPT_CPTD_CD END,
  LAW_CAT_CD = CASE WHEN LAW_CAT_CD = '(null)' THEN NULL ELSE LAW_CAT_CD END,
  BORO_NM = CASE WHEN BORO_NM = '(null)' THEN NULL ELSE BORO_NM END,
  LOC_OF_OCCUR_DESC = CASE WHEN LOC_OF_OCCUR_DESC = '(null)' THEN NULL ELSE LOC_OF_OCCUR_DESC END,
  PREM_TYP_DESC = CASE WHEN PREM_TYP_DESC = '(null)' THEN NULL ELSE PREM_TYP_DESC END,
  SUSP_AGE_GROUP = CASE WHEN SUSP_AGE_GROUP = '(null)' THEN NULL ELSE SUSP_AGE_GROUP END,
  SUSP_RACE = CASE WHEN SUSP_RACE = '(null)' THEN NULL ELSE SUSP_RACE END,
  SUSP_SEX = CASE WHEN SUSP_SEX = '(null)' THEN NULL ELSE SUSP_SEX END,
  VIC_AGE_GROUP = CASE WHEN VIC_AGE_GROUP = '(null)' THEN NULL ELSE VIC_AGE_GROUP END,
  VIC_RACE = CASE WHEN VIC_RACE = '(null)' THEN NULL ELSE VIC_RACE END,
  VIC_SEX = CASE WHEN VIC_SEX = '(null)' THEN NULL ELSE VIC_SEX END
;

DELETE FROM nypd_complaints
WHERE
  OFNS_DESC IS NULL OR
  CRM_ATPT_CPTD_CD IS NULL OR
  LAW_CAT_CD IS NULL OR
  BORO_NM IS NULL OR
  LOC_OF_OCCUR_DESC IS NULL OR
  PREM_TYP_DESC IS NULL OR
  SUSP_AGE_GROUP IS NULL OR
  SUSP_RACE IS NULL OR
  SUSP_SEX IS NULL OR
  VIC_AGE_GROUP IS NULL OR
  VIC_RACE IS NULL OR
  VIC_SEX IS NULL;

-- 1. Crime Rate by Borough
SELECT BORO_NM, COUNT(CMPLNT_NUM) AS Crime_Count
FROM nypd_complaints
GROUP BY BORO_NM
ORDER BY Crime_Count DESC;

-- 2. Count the number of complaints by offense description for the specific year 2020
SELECT OFNS_DESC, COUNT(CMPLNT_NUM) AS Complaint_Count
FROM nypd_complaints
WHERE Year = 2020
GROUP BY OFNS_DESC
ORDER BY Complaint_Count DESC;

-- 3. Crime Count by Crime Attempted/Completed Status
SELECT CRM_ATPT_CPTD_CD, COUNT(CMPLNT_NUM) AS Crime_Count
FROM nypd_complaints
GROUP BY CRM_ATPT_CPTD_CD;
		
-- 4. List of Holidays in 2015
SELECT *
FROM ny_holidays
WHERE Year = 2015;

-- 5. Top Crime Categories and their Occurrence Count
SELECT OFNS_DESC, COUNT(CMPLNT_NUM) AS Crime_Count
FROM nypd_complaints
GROUP BY OFNS_DESC
ORDER BY Crime_Count DESC
LIMIT 10;

-- 6. Crime Count by Borough and Suspect Race
SELECT BORO_NM, SUSP_RACE, COUNT(CMPLNT_NUM) AS Crime_Count
FROM nypd_complaints
WHERE SUSP_RACE IS NOT NULL
GROUP BY BORO_NM, SUSP_RACE
ORDER BY BORO_NM, Crime_Count DESC;

